# H2 Server Mode (Standalone Server)
spring:
  application:
    name: member-order-payment-system
  
  datasource:
    url: jdbc:h2:tcp://localhost:9092/./data/h2server;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG
